version: "3.9"
services:
  laravel:
    build:
      context: ./Hefesto-Backend
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - APP_DEBUG=true
      - APP_KEY=base64:somekey==base64:klPBaYGK/28Rm8B2kc4OuTA2mcMNJl03mkpr+O1R1aI=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=user
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - app-network

  frontend:
    build:
      context: ./Hefesto-Frontend
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - laravel
    environment:
      - VUE_APP_API_URL=http://laravel:8000/api

networks:
  app-network:
    driver: bridge
